DROP TABLE IF EXISTS tache;
DROP TABLE IF EXISTS categorie;

CREATE TABLE IF NOT EXISTS categorie(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tache(
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    description TEXT,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_fin DATE, -- à préciser
    categorie_id INT NOT NULL,
    statut ENUM('A_FAIRE', 'EN_COURS', 'TERMINE') DEFAULT 'A_FAIRE',
    FOREIGN KEY (categorie_id) REFERENCES categorie(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;